services:
  goup:
    image: ghcr.io/teejmcsteez/goup:latest
    container_name: goup
    restart: unless-stopped
    ports:
      - "8101:8101"
    volumes:
      - ./config:/app/config
      - goup-data:/app/data
      # Optional: Remove the line below to store configuration file in the image volume
      - ./services.yml:/app/config/services.yml
    # Optional: set timezone for accurate timestamps
    environment:
      - TZ=America/New_York

volumes:
  goup-data:
