// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get all recent service data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.ServiceData"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get full configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ConfigData"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/backoff": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get the global trigger backoff period",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.BackoffPayload"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set the global trigger backoff period",
                "parameters": [
                    {
                        "description": "Backoff duration, e.g. 5m; blank disables the global backoff",
                        "name": "backoff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.BackoffPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/discord": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set Discord trigger configuration",
                "parameters": [
                    {
                        "description": "Discord config",
                        "name": "discord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.DiscordTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove Discord trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/gotify": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set Gotify trigger configuration",
                "parameters": [
                    {
                        "description": "Gotify config",
                        "name": "gotify",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.GotifyTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove Gotify trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/ha": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set Home Assistant trigger configuration",
                "parameters": [
                    {
                        "description": "Home Assistant config",
                        "name": "ha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.HATrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove Home Assistant trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/mqtt": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set MQTT trigger configuration",
                "parameters": [
                    {
                        "description": "MQTT config",
                        "name": "mqtt",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.MQTTTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove MQTT trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/service": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update a monitored service",
                "parameters": [
                    {
                        "description": "Old name + new service definition",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ServiceUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Add a monitored service",
                "parameters": [
                    {
                        "description": "Service definition",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.Service"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Delete a monitored service",
                "parameters": [
                    {
                        "description": "Service definition",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.Service"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/service/active": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get a service's active (fetch enabled) state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name to look up",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Service"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Enable or disable fetch for a service",
                "parameters": [
                    {
                        "description": "Service to toggle active state",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.Service"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/size": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get the configured database max size",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DatabaseSizePayload"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update the database max size",
                "parameters": [
                    {
                        "description": "Size string (e.g. 1kb, 2mb, 3gb)",
                        "name": "db_max_size",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.DatabaseSizePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/slack": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set Slack trigger configuration",
                "parameters": [
                    {
                        "description": "Slack config",
                        "name": "slack",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.SlackTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove Slack trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/smtp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set SMTP trigger configuration",
                "parameters": [
                    {
                        "description": "SMTP config",
                        "name": "smtp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.SMTPTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove SMTP trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/telegram": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set Telegram trigger configuration",
                "parameters": [
                    {
                        "description": "Telegram config",
                        "name": "telegram",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.TelegramTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove Telegram trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/webhook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set webhook trigger configuration",
                "parameters": [
                    {
                        "description": "Webhook config",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.WebhookTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Remove webhook trigger configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/db/clear": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Clear all data from the database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/db/persist": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Get whether database persistence is enabled",
                "responses": {
                    "200": {
                        "description": "persistence enabled",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Toggle database persistence",
                "responses": {
                    "200": {
                        "description": "empty body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/db/size": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Get database file size in bytes for regular files; system-dependent for others https://pkg.go.dev/io/fs#FileInfo.Size",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DatabaseSizePayload"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/errors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get error log entries",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max number of results (0 = all)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.ServiceData"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/fire": {
            "post": {
                "description": "Fires the scheduler immediately instead of waiting for the next scheduled interval",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Manually trigger a service data fetch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/rt": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get response time history for all services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.ServiceResponseTime"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/schedule": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Get the polling schedule",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ScheduleState"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Update the polling schedule",
                "parameters": [
                    {
                        "description": "Schedule to set",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.ScheduleState"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{updated:true}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/status": {
            "get": {
                "description": "Returns all currently down services.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get current service status returning any downed services or null for no services down",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ServiceResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tls": {
            "get": {
                "description": "Returns all TLS certificates - null if none",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Gets all TLS certificate(s)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.TlsStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/uptime": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get uptime averages for all services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.AverageData"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.BackoffPayload": {
            "type": "object",
            "properties": {
                "backoff_period": {
                    "type": "string"
                }
            }
        },
        "server.DatabaseSizePayload": {
            "type": "object",
            "properties": {
                "db_max_size": {
                    "type": "string"
                }
            }
        },
        "server.ServiceUpdatePayload": {
            "type": "object",
            "properties": {
                "old_name": {
                    "type": "string"
                },
                "service": {
                    "$ref": "#/definitions/utils.Service"
                }
            }
        },
        "utils.AverageData": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "utils.ConfigData": {
            "type": "object",
            "properties": {
                "backoff_period": {
                    "type": "string"
                },
                "discord": {
                    "$ref": "#/definitions/utils.DiscordTrigger"
                },
                "gotify": {
                    "$ref": "#/definitions/utils.GotifyTrigger"
                },
                "ha": {
                    "$ref": "#/definitions/utils.HATrigger"
                },
                "mqtt": {
                    "$ref": "#/definitions/utils.MQTTTrigger"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/utils.Service"
                    }
                },
                "slack": {
                    "$ref": "#/definitions/utils.SlackTrigger"
                },
                "smtp": {
                    "$ref": "#/definitions/utils.SMTPTrigger"
                },
                "telegram": {
                    "$ref": "#/definitions/utils.TelegramTrigger"
                },
                "webhook": {
                    "$ref": "#/definitions/utils.WebhookTrigger"
                }
            }
        },
        "utils.DatabaseSizePayload": {
            "type": "object",
            "properties": {
                "size_string": {
                    "type": "integer"
                }
            }
        },
        "utils.DiscordTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "discord_Auth": {
                    "description": "Can be Bot \u003ctoken\u003e or Bearer \u003ctoken\u003e",
                    "type": "string"
                },
                "discord_Channel": {
                    "description": "For now only one channel is supported\nHowever, if needed many channels would be optional\nJust need to use a string array over string pointer to send message to all channels",
                    "type": "string"
                }
            }
        },
        "utils.GotifyTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "gotify_Application": {
                    "type": "string"
                },
                "gotify_Priority": {
                    "type": "integer"
                },
                "gotify_Server": {
                    "type": "string"
                },
                "gotify_Title": {
                    "type": "string"
                },
                "gotify_Token": {
                    "type": "string"
                }
            }
        },
        "utils.HATrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "ha_Token": {
                    "type": "string"
                },
                "ha_URL": {
                    "type": "string"
                }
            }
        },
        "utils.MQTTTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "mqtt_broker": {
                    "type": "string"
                },
                "mqtt_key": {
                    "type": "string"
                },
                "mqtt_username": {
                    "type": "string"
                }
            }
        },
        "utils.SMTPTrigger": {
            "type": "object",
            "properties": {
                "app_Password": {
                    "type": "string"
                },
                "backoff_Period": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "smtpserver": {
                    "type": "string"
                }
            }
        },
        "utils.ScheduleState": {
            "type": "object",
            "properties": {
                "interval": {
                    "type": "string"
                },
                "timespan": {
                    "type": "integer"
                }
            }
        },
        "utils.Service": {
            "type": "object",
            "properties": {
                "API_KEY": {
                    "type": "string"
                },
                "API_URL": {
                    "type": "string"
                },
                "Active": {
                    "description": "Active is a *bool so an unset value (nil) can default to true,\ndistinct from an explicit ` + "`" + `active: false` + "`" + `.",
                    "type": "boolean"
                },
                "Description": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Retry_Requests": {
                    "type": "integer"
                },
                "SkipInsecure": {
                    "type": "boolean"
                },
                "URL": {
                    "type": "string"
                },
                "Valid_Responses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "utils.ServiceData": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "data": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "response_time": {
                    "type": "string"
                },
                "skip_insecure": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "utils.ServiceResponse": {
            "type": "object",
            "properties": {
                "downed_services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.ServiceData"
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.ServiceData"
                    }
                },
                "tls_status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.TlsStatus"
                    }
                }
            }
        },
        "utils.ServiceResponseTime": {
            "type": "object",
            "properties": {
                "response_time": {
                    "type": "string"
                },
                "service_data": {
                    "$ref": "#/definitions/utils.ServiceData"
                }
            }
        },
        "utils.SlackTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "bot_Username": {
                    "type": "string"
                },
                "slack_Channel": {
                    "type": "string"
                },
                "slack_Token": {
                    "type": "string"
                }
            }
        },
        "utils.TelegramTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "telegram_Channel_Id": {
                    "type": "string"
                },
                "telegram_Token": {
                    "type": "string"
                }
            }
        },
        "utils.TlsStatus": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "first_seen": {
                    "type": "string"
                },
                "is_expired": {
                    "type": "boolean"
                },
                "issuer": {
                    "type": "string"
                },
                "last_checked": {
                    "type": "string"
                },
                "not_after": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "utils.WebhookTrigger": {
            "type": "object",
            "properties": {
                "backoff_Period": {
                    "type": "string"
                },
                "custom_message": {
                    "type": "string"
                },
                "webhook_key_string": {
                    "description": "Can use any authorization header string\nEx: Basic \u003ccreds\u003e/Digest username=\u003cusername\u003e.../Bearer \u003ctoken_string\u003e",
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8101",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "goUp API",
	Description:      "REST API for monitoring service uptime, response times, and managing configuration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
