// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type ServiceDatum struct {
	ID                  int64
	ServiceUrl          sql.NullString
	ServiceName         sql.NullString
	ServiceDescription  sql.NullString
	ServiceHttpResponse sql.NullString
	ServiceApiResponse  sql.NullString
	ServiceResponseTime sql.NullInt64
	Timestamp           sql.NullString
	Error               int64
	Active              int64
}

type TlsStatus struct {
	ServiceName string
	Fingerprint string
	NotAfter    int64
	Subject     sql.NullString
	Issuer      sql.NullString
	IsExpired   int64
	Chain       sql.NullString
	FirstSeen   string
	LastChecked string
}
