// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type ServiceDatum struct {
	ID                  int64
	ServiceUrl          sql.NullString
	ServiceName         sql.NullString
	ServiceDescription  sql.NullString
	ServiceHttpResponse sql.NullString
	ServiceApiResponse  sql.NullString
	ServiceResponseTime sql.NullInt64
	Timestamp           sql.NullString
	Error               int64
}
