// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const cleanup = `-- name: Cleanup :exec
DELETE FROM service_data WHERE service_name NOT IN (/*SLICE:names*/?)
`

func (q *Queries) Cleanup(ctx context.Context, names []sql.NullString) error {
	query := cleanup
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const clearServiceData = `-- name: ClearServiceData :exec
DELETE FROM service_data
`

func (q *Queries) ClearServiceData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearServiceData)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM service_data WHERE service_name = ?
`

func (q *Queries) DeleteService(ctx context.Context, serviceName sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteService, serviceName)
	return err
}

const deleteServiceTlsStatus = `-- name: DeleteServiceTlsStatus :exec
DELETE FROM tls_status WHERE service_name = ?
`

func (q *Queries) DeleteServiceTlsStatus(ctx context.Context, serviceName string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceTlsStatus, serviceName)
	return err
}

const getAllData = `-- name: GetAllData :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error, active FROM service_data
`

func (q *Queries) GetAllData(ctx context.Context) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAllData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataForService = `-- name: GetDataForService :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error, active FROM service_data WHERE service_name = ? ORDER BY id DESC
`

func (q *Queries) GetDataForService(ctx context.Context, serviceName sql.NullString) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getDataForService, serviceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorDataAsc = `-- name: GetErrorDataAsc :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error, active FROM service_data WHERE error = 1 ORDER BY timestamp ASC LIMIT ?
`

func (q *Queries) GetErrorDataAsc(ctx context.Context, limit int64) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getErrorDataAsc, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorDataDesc = `-- name: GetErrorDataDesc :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error, active FROM service_data WHERE error = 1 ORDER BY timestamp DESC LIMIT ?
`

func (q *Queries) GetErrorDataDesc(ctx context.Context, limit int64) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getErrorDataDesc, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentData = `-- name: GetRecentData :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error, active FROM service_data WHERE id IN (
	SELECT MAX(id) FROM service_data GROUP BY service_name
) ORDER BY id DESC
`

func (q *Queries) GetRecentData(ctx context.Context) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getRecentData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceTlsStatus = `-- name: GetServiceTlsStatus :one
SELECT service_name, fingerprint, not_after, subject, issuer, is_expired, chain, first_seen, last_checked FROM tls_status WHERE service_name = ? LIMIT 1
`

func (q *Queries) GetServiceTlsStatus(ctx context.Context, serviceName string) (TlsStatus, error) {
	row := q.db.QueryRowContext(ctx, getServiceTlsStatus, serviceName)
	var i TlsStatus
	err := row.Scan(
		&i.ServiceName,
		&i.Fingerprint,
		&i.NotAfter,
		&i.Subject,
		&i.Issuer,
		&i.IsExpired,
		&i.Chain,
		&i.FirstSeen,
		&i.LastChecked,
	)
	return i, err
}

const getTlsStatus = `-- name: GetTlsStatus :many
SELECT service_name, fingerprint, not_after, subject, issuer, is_expired, chain, first_seen, last_checked FROM tls_status
`

func (q *Queries) GetTlsStatus(ctx context.Context) ([]TlsStatus, error) {
	rows, err := q.db.QueryContext(ctx, getTlsStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TlsStatus
	for rows.Next() {
		var i TlsStatus
		if err := rows.Scan(
			&i.ServiceName,
			&i.Fingerprint,
			&i.NotAfter,
			&i.Subject,
			&i.Issuer,
			&i.IsExpired,
			&i.Chain,
			&i.FirstSeen,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertData = `-- name: InsertData :exec
INSERT INTO service_data (service_url, service_name, service_description, service_HTTP_response, service_API_response, service_response_time, timestamp, error, active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDataParams struct {
	ServiceUrl          sql.NullString
	ServiceName         sql.NullString
	ServiceDescription  sql.NullString
	ServiceHttpResponse sql.NullString
	ServiceApiResponse  sql.NullString
	ServiceResponseTime sql.NullInt64
	Timestamp           sql.NullString
	Error               int64
	Active              int64
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) error {
	_, err := q.db.ExecContext(ctx, insertData,
		arg.ServiceUrl,
		arg.ServiceName,
		arg.ServiceDescription,
		arg.ServiceHttpResponse,
		arg.ServiceApiResponse,
		arg.ServiceResponseTime,
		arg.Timestamp,
		arg.Error,
		arg.Active,
	)
	return err
}

const insertTlsStatus = `-- name: InsertTlsStatus :exec
INSERT INTO tls_status (service_name, fingerprint, not_after, subject, issuer,
                        is_expired, chain, first_seen, last_checked)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(service_name) DO UPDATE SET
    fingerprint  = excluded.fingerprint,
    not_after    = excluded.not_after,
    subject      = excluded.subject,
    issuer       = excluded.issuer,
    is_expired   = excluded.is_expired,
    chain        = excluded.chain,
    last_checked = excluded.last_checked,
    first_seen   = CASE
        WHEN tls_status.fingerprint = excluded.fingerprint
        THEN tls_status.first_seen   -- same cert, keep it
        ELSE excluded.first_seen     -- renewed, resets, giving cert age for free
    END
`

type InsertTlsStatusParams struct {
	ServiceName string
	Fingerprint string
	NotAfter    int64
	Subject     sql.NullString
	Issuer      sql.NullString
	IsExpired   int64
	Chain       sql.NullString
	FirstSeen   string
	LastChecked string
}

func (q *Queries) InsertTlsStatus(ctx context.Context, arg InsertTlsStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertTlsStatus,
		arg.ServiceName,
		arg.Fingerprint,
		arg.NotAfter,
		arg.Subject,
		arg.Issuer,
		arg.IsExpired,
		arg.Chain,
		arg.FirstSeen,
		arg.LastChecked,
	)
	return err
}

const serviceRename = `-- name: ServiceRename :exec
UPDATE service_data SET service_name = ? WHERE service_name = ?
`

type ServiceRenameParams struct {
	ServiceName   sql.NullString
	ServiceName_2 sql.NullString
}

func (q *Queries) ServiceRename(ctx context.Context, arg ServiceRenameParams) error {
	_, err := q.db.ExecContext(ctx, serviceRename, arg.ServiceName, arg.ServiceName_2)
	return err
}

const updateTlsServiceName = `-- name: UpdateTlsServiceName :exec
UPDATE tls_status SET service_name = ? WHERE service_name = ?
`

type UpdateTlsServiceNameParams struct {
	ServiceName   string
	ServiceName_2 string
}

func (q *Queries) UpdateTlsServiceName(ctx context.Context, arg UpdateTlsServiceNameParams) error {
	_, err := q.db.ExecContext(ctx, updateTlsServiceName, arg.ServiceName, arg.ServiceName_2)
	return err
}
