// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const cleanup = `-- name: Cleanup :exec
DELETE FROM service_data WHERE service_name NOT IN (/*SLICE:names*/?)
`

func (q *Queries) Cleanup(ctx context.Context, names []sql.NullString) error {
	query := cleanup
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const clearServiceData = `-- name: ClearServiceData :exec
DELETE FROM service_data
`

func (q *Queries) ClearServiceData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearServiceData)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM service_data WHERE service_name = ?
`

func (q *Queries) DeleteService(ctx context.Context, serviceName sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteService, serviceName)
	return err
}

const getAllData = `-- name: GetAllData :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error FROM service_data
`

func (q *Queries) GetAllData(ctx context.Context) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAllData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataForService = `-- name: GetDataForService :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error FROM service_data WHERE service_name = ? ORDER BY id DESC
`

func (q *Queries) GetDataForService(ctx context.Context, serviceName sql.NullString) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getDataForService, serviceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorDataAsc = `-- name: GetErrorDataAsc :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error FROM service_data WHERE error = 1 ORDER BY timestamp ASC LIMIT ?
`

func (q *Queries) GetErrorDataAsc(ctx context.Context, limit int64) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getErrorDataAsc, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorDataDesc = `-- name: GetErrorDataDesc :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error FROM service_data WHERE error = 1 ORDER BY timestamp DESC LIMIT ?
`

func (q *Queries) GetErrorDataDesc(ctx context.Context, limit int64) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getErrorDataDesc, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentData = `-- name: GetRecentData :many
SELECT id, service_url, service_name, service_description, service_http_response, service_api_response, service_response_time, timestamp, error FROM service_data WHERE id IN (
	SELECT MAX(id) FROM service_data GROUP BY service_name
) ORDER BY id DESC
`

func (q *Queries) GetRecentData(ctx context.Context) ([]ServiceDatum, error) {
	rows, err := q.db.QueryContext(ctx, getRecentData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDatum
	for rows.Next() {
		var i ServiceDatum
		if err := rows.Scan(
			&i.ID,
			&i.ServiceUrl,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.ServiceHttpResponse,
			&i.ServiceApiResponse,
			&i.ServiceResponseTime,
			&i.Timestamp,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertData = `-- name: InsertData :exec
INSERT INTO service_data (service_url, service_name, service_description, service_HTTP_response, service_API_response, service_response_time, timestamp, error) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDataParams struct {
	ServiceUrl          sql.NullString
	ServiceName         sql.NullString
	ServiceDescription  sql.NullString
	ServiceHttpResponse sql.NullString
	ServiceApiResponse  sql.NullString
	ServiceResponseTime sql.NullInt64
	Timestamp           sql.NullString
	Error               int64
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) error {
	_, err := q.db.ExecContext(ctx, insertData,
		arg.ServiceUrl,
		arg.ServiceName,
		arg.ServiceDescription,
		arg.ServiceHttpResponse,
		arg.ServiceApiResponse,
		arg.ServiceResponseTime,
		arg.Timestamp,
		arg.Error,
	)
	return err
}

const serviceRename = `-- name: ServiceRename :exec
UPDATE service_data SET service_name = ? WHERE service_name = ?
`

type ServiceRenameParams struct {
	ServiceName   sql.NullString
	ServiceName_2 sql.NullString
}

func (q *Queries) ServiceRename(ctx context.Context, arg ServiceRenameParams) error {
	_, err := q.db.ExecContext(ctx, serviceRename, arg.ServiceName, arg.ServiceName_2)
	return err
}
